### ISSUE TITLE
Program fails on special character [ in path

### ISSUE THREAD

**Issue by coboba123** [watermelonwolverine/fvttoptimizer#1]
First off, thank you so much for making this. 

I am trying to use the following command:
`fvttoptimizer.exe --recursive 'C:\Users\cnguy\AppData\Local\FoundryVTT\Data\Battle Maps'`

and I am getting this return:
`An unexpected error occurred: expected str, bytes or os.PathLike object, not NoneType`

Your documentation implies this is supported, as this command works without the "--recursive" flag, so maybe there is an issue with spaces in paths and the recursive function? 

Thank you.

**Comment by coboba123** [comment]
![image](https://user-images.githubusercontent.com/12433299/162589426-94f093f8-9446-49dc-bec0-9b6995047c6c.png)

For reference here is what the folder looks like

**Comment by watermelonwolverine** [comment]
Can you add the --verbose-info or --verbose-debug option and check where it fails? This should also output a stack trace which would be very useful. Spaces shouldn't a problem, they are covered by tests.

**Comment by coboba123** [comment]
--verbose-info
`./fvttoptimizer.exe --recursive --verbose-info 'C:\Users\cnguy\AppData\Local\FoundryVTT\Data\Battle Maps'
root - ERROR - expected str, bytes or os.PathLike object, not NoneType
An unexpected error occurred: expected str, bytes or os.PathLike object, not NoneType`

--verbose-debug
`./fvttoptimizer.exe --recursive --verbose-debug 'C:\Users\cnguy\AppData\Local\FoundryVTT\Data\Battle Maps'
root - DEBUG - Got arguments ['C:\\Users\\cnguy\\AppData\\Local\\FoundryVTT\\Data\\FVTT Optimizer\\fvttoptimizer.exe', '--recursive', '--verbose-debug', 'C:\\Users\\cnguy\\AppData\\Local\\FoundryVTT\\Data\\Battle Maps']
root - DEBUG - Reading config from: C:\Users\cnguy\AppData\Local\FoundryVTT\Data\FVTT Optimizer\fvttoptimizer.conf
root - DEBUG - Running with target_path='C:\Users\cnguy\AppData\Local\FoundryVTT\Data\Battle Maps', config='{'_RunConfig__program_config': {'_ProgramConfigImpl__abs_path_to_foundry_data': 'C:\\Users\\cnguy\\AppData\\Local\\FoundryVTT\\Data'}, 'skip_existing': False, 'skip_webp': False, 'recursive': True, 'quality': 75, 'override_percent': 25}'
root - ERROR - expected str, bytes or os.PathLike object, not NoneType
An unexpected error occurred: expected str, bytes or os.PathLike object, not NoneType`

**Comment by watermelonwolverine** [comment]
Try the new released. Should be fixed now. Problem was the special character [

**Comment by coboba123** [comment]
It works now, thank you for your work
