### ISSUE TITLE
Suggestion: Print which file it is working on during the conversion process. 

### ISSUE THREAD

**Issue by coboba123** [watermelonwolverine/fvttoptimizer#3]
I think it would be nice to have some kind of progress indicator to show what its working on in the command prompt window. The easiest way to have this would simply just print the name of the file that is being worked on when it gets to it. When working on folders with lots of images, its nice to know its not frozen or hanging on something. 

Thank you!

**Comment by watermelonwolverine** [comment]
Use --verbose-info or --verbose-debug

**Comment by coboba123** [comment]
Oh nice thank you.
