### ISSUE TITLE
Missing config file

### ISSUE THREAD

**Issue by tonydero** [watermelonwolverine/fvttoptimizer#5]
When running on an image file I get the error:

`Missing config file. Could not find /etc/fvttoptimizer.conf`

Tried running all three release versions on Arch Linux with Python 3.10.4 and get the same error every time.

I'm not seeing any mention of a config file in the readme. Am I missing something?

**Comment by watermelonwolverine** [comment]
Are you sure?:

https://github.com/watermelonwolverine/fvttoptimizer#option-2-manual-installation

**Comment by tonydero** [comment]
That would definitely be missing something... thanks and apologies...
